version: 2.1
orbs:
  android: circleci/android@3.0.0

jobs:
  android:
    executor:
      name: android/android-machine
      tag: 2024.01.1
      resource-class: large
    steps:
      - checkout
      - run:
          name: List Files
          command: ls -lah

workflows:
  build:
    jobs:
      - android
